# Generated by Django 2.0.2 on 2018-02-27 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
